# ======= How to run: 
# boburciu@WX-5CG020BDT2: ~$ cd ~/netbox-ansible-automation
# boburciu@WX-5CG020BDT2:~/netbox-ansible-automation$ ansible-playbook -i ./hosts -v create_device_wMgmtIntIP_inRack_inTenant_inRack_inSite.yml
# boburciu@WX-5CG020BDT2:~/netbox-ansible-automation$ ansible-playbook -i ./hosts -v create_device_wMgmtIntIP_inRack_inTenant_inRack_inSite.yml -e 'device_hostname="SWH-TOR-R1-02" device_serial="2102350JAS6TJ8000515" device_position_in_rack=33'
---
- name: Add an device with its primary interface IP assigned, in a specific rack, dedicated tenant and site, with all dependencies created at playbook runtime
  hosts: docker_netbox_19216820023
  gather_facts: False  
  tasks:
    - include_vars: external_vars_NE40E.yml  # where "url_var: http://192.168.200.23:8001/"

- name: 1st, create the tags to be used
  import_playbook: create_tag.yml

- name: 2nd, create the region (prereq. for site)
  import_playbook: create_region.yml
  vars:
    region_name: EMEA

- name: 3rd, create the site (prereq. for rack group)
  import_playbook: create_site.yml
  vars:
    site_description: 'Orange DC in Romania, Bucharest' # does not take precendence tp the included vars, which have to be overwritten with -e / --extra-var at playbook runtime
  
- name: 4th, create the rack group, rack role and rack
  import_playbook: create_rack.yml

- name: 5th, create the tenant group and tenant
  import_playbook: create_tenant.yml

- name: 6th, create the device
  import_playbook: create_device.yml

- name: 7th, create the Mgmt interface
  import_playbook: create_interface.yml

- name: 8th, create the VRF
  import_playbook: create_vrf.yml

- name: 9th, create the IP address 
  import_playbook: create_ip_addr.yml 

- name: 10th, update the device by attaching the primary IP address to its Mgmt interface
  import_playbook: create_device.yml
