# ======= How to run w non-root Ansible user: 
# boburciu@WX-5CG020BDT2: ~$ cd ~/netbox-ansible-automation
# boburciu@WX-5CG020BDT2:~/netbox-ansible-automation$ ansible-playbook -i ./hosts -v main_organization.yml -e 'site_description="Orange DC in Romania, Bucharest"'
# possibly with --become --ask-become-pass 
---
- name: Add an IP address entry in a specific VRF, in a specific Tenant, all 3 dependencies created at playbook runtime
  hosts: docker_netbox_19216820023
  gather_facts: False  
  tasks:
    - include_vars: external_vars.yml  # where "url_var: http://192.168.200.23:8001/"

- name: 1st, create the tags
  import_playbook: create_tag.yml
  vars:
    tag3_name: oiaas
    tag3_description: "Orange IaaS deployment"
    tag3_color: FFA500  # RGB color in hexadecimal  

- name: 2nd, create the region (prereq. for site)
  import_playbook: create_region.yml
  vars:
    region_name: EMEA

- name: 3rd, create the site (prereq. for rack group)
  import_playbook: create_site.yml
  vars:
    site_description: 'Orange DC in Romania, Bucharest' # does not take precendence tp the included vars, which have to be overwritten with -e / --extra-var at playbook runtime
  
- name: 4th, create the rack group, rack role and rack
  import_playbook: create_rack.yml

